//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NOTAM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Entity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Entity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NOTAM.Properties.Entity", typeof(Entity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not authorized for this action.
        /// </summary>
        internal static string Action_NotAuthorized {
            get {
                return ResourceManager.GetString("Action_NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Aerodom.
        /// </summary>
        internal static string AerodomViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AerodomViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Aftn.
        /// </summary>
        internal static string AftnViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AftnViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not save Aftn.
        /// </summary>
        internal static string AftnViewModel_Exception_CannotSave {
            get {
                return ResourceManager.GetString("AftnViewModel_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Aerodoms.
        /// </summary>
        internal static string AllAerodomsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllAerodomsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Aftns.
        /// </summary>
        internal static string AllAftnsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllAftnsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All NOTAMS.
        /// </summary>
        internal static string AllArchAndValidNotamsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllArchAndValidNotamsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Countries.
        /// </summary>
        internal static string AllCountriesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllCountriesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All FIRs.
        /// </summary>
        internal static string AllFIRsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllFIRsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All NOTAM Codes.
        /// </summary>
        internal static string AllNotamCodesViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllNotamCodesViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALID NOTAMS.
        /// </summary>
        internal static string AllNotamsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllNotamsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Origins.
        /// </summary>
        internal static string AllOriginsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllOriginsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid SNOWTAMS.
        /// </summary>
        internal static string AllSnowtamsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllSnowtamsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        internal static string AllUsersViewModel_DisplayName {
            get {
                return ResourceManager.GetString("AllUsersViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive NOTAMS.
        /// </summary>
        internal static string ArchiveNotamsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ArchiveNotamsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive SNOWTAMS.
        /// </summary>
        internal static string ArchiveSnowtamsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("ArchiveSnowtamsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C NOTAMS.
        /// </summary>
        internal static string CNotamViewModel_DisplayName {
            get {
                return ResourceManager.GetString("CNotamViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Country.
        /// </summary>
        internal static string CountryViewModel_DisplayName {
            get {
                return ResourceManager.GetString("CountryViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New FIR.
        /// </summary>
        internal static string FIRViewModel_DisplayName {
            get {
                return ResourceManager.GetString("FIRViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold NOTAMS.
        /// </summary>
        internal static string HoldNotamsViewModel_DisplayName {
            get {
                return ResourceManager.GetString("HoldNotamsViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C NOTAM.
        /// </summary>
        internal static string MainWindowViewModel_Command_CancelNotam {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_CancelNotam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Aerodom.
        /// </summary>
        internal static string MainWindowViewModel_Command_NewAerodom {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_NewAerodom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Aftn.
        /// </summary>
        internal static string MainWindowViewModel_Command_NewAftn {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_NewAftn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New FIR.
        /// </summary>
        internal static string MainWindowViewModel_Command_NewFIR {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_NewFIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Style.
        /// </summary>
        internal static string MainWindowViewModel_Command_NewFreeStyle {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_NewFreeStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N NOTAM.
        /// </summary>
        internal static string MainWindowViewModel_Command_NewNotam {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_NewNotam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New NOTAM Code.
        /// </summary>
        internal static string MainWindowViewModel_Command_NewNotamCode {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_NewNotamCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Origin.
        /// </summary>
        internal static string MainWindowViewModel_Command_NewOrigins {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_NewOrigins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        internal static string MainWindowViewModel_Command_NewUser {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R NOTAM.
        /// </summary>
        internal static string MainWindowViewModel_Command_ReplaceNotam {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ReplaceNotam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run archive.
        /// </summary>
        internal static string MainWindowViewModel_Command_RunArchive {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_RunArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Summary.
        /// </summary>
        internal static string MainWindowViewModel_Command_RunSummary {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_RunSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International NOTAMS.
        /// </summary>
        internal static string MainWindowViewModel_Command_SearchIntlNotams {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_SearchIntlNotams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string MainWindowViewModel_Command_Setting {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New SNOWTAM.
        /// </summary>
        internal static string MainWindowViewModel_Command_Snowtam {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_Snowtam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Aerodoms.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllAerodoms {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllAerodoms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Aftns.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllAftns {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllAftns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive NOTAMS.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllArchiveNotams {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllArchiveNotams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive SNOWTAMS.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllArichiveSnowtams {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllArichiveSnowtams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All FIRs.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllFIRs {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllFIRs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold NOTAMS.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllHoldNotams {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllHoldNotams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All NOTAM Codes.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllNotamCodes {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllNotamCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VALID NOTAMS.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllNotams {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllNotams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Origins.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllOrigins {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllOrigins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid SNOWTAMS.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllSnowtams {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllSnowtams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        internal static string MainWindowViewModel_Command_ViewAllUsers {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Command_ViewAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIS Admin.
        /// </summary>
        internal static string MainWindowViewModel_DisplayName {
            get {
                return ResourceManager.GetString("MainWindowViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New NOTAM Code.
        /// </summary>
        internal static string NotamCodeViewModel_DisplayName {
            get {
                return ResourceManager.GetString("NotamCodeViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New NOTAM Detail.
        /// </summary>
        internal static string NotamDetailViewModel_DisplayName {
            get {
                return ResourceManager.GetString("NotamDetailViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search NOTAMS     .
        /// </summary>
        internal static string NotamSearchViewModel_DisplayName {
            get {
                return ResourceManager.GetString("NotamSearchViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notam Summary Report.
        /// </summary>
        internal static string NotamSummary_DisplayName {
            get {
                return ResourceManager.GetString("NotamSummary_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New NOTAM.
        /// </summary>
        internal static string NotamViewModel_DisplayName {
            get {
                return ResourceManager.GetString("NotamViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not load an invalid NOTAM.
        /// </summary>
        internal static string NotamViewModel_Exception_CannotLoad {
            get {
                return ResourceManager.GetString("NotamViewModel_Exception_CannotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notam status is not valid for being archived.
        /// </summary>
        internal static string NotValidStateForArchive {
            get {
                return ResourceManager.GetString("NotValidStateForArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Origin.
        /// </summary>
        internal static string OriginViewModel_DisplayName {
            get {
                return ResourceManager.GetString("OriginViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save an invalid Origin..
        /// </summary>
        internal static string OriginViewModel_Exception_CannotSave {
            get {
                return ResourceManager.GetString("OriginViewModel_Exception_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R NOTAM.
        /// </summary>
        internal static string RNotamViewModel_DisplayName {
            get {
                return ResourceManager.GetString("RNotamViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New SNOWTAM.
        /// </summary>
        internal static string SnowtamViewModel_DisplayName {
            get {
                return ResourceManager.GetString("SnowtamViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        internal static string UserViewModel_DisplayName {
            get {
                return ResourceManager.GetString("UserViewModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string UserViewModel_SettingName {
            get {
                return ResourceManager.GetString("UserViewModel_SettingName", resourceCulture);
            }
        }
    }
}
